### ISSUE TITLE
Arreglar valoración cliente/owner

### ISSUE THREAD

**Issue by AMC112002** [ISPP-23-24-Grupo-3/musclemate-frontend#100]
Arreglar que la valoración que ponga el cliente que contenga mitades de estrellas aparezca igual en el owner, puesto que ahora si el cliente puntúa una valoración de 3.5 se le redondea al owner en enteros (3 o 4).

**Comment by lemonada02** [comment]
Habrá sido un fallo, probandolo de nuevo no se repite el fallo.

La issue se cerrará como completada
