### ISSUE TITLE
Página de Terminos y condiciones

### ISSUE THREAD

**Issue by davdelcar** [ISPP-23-24-Grupo-3/musclemate-frontend#108]
### Requisitos a cumplir

- [x] Hacer en una ruta pública,una página donde aparezca los terminos y condiciones redactados
- [x] En el regisro de owner añadir un checkbox aceptando dichos términos y añadir un hipervinculo al texto al lado que lo lleve a la página de terminos y condiciones

**Comment by agudevbon** [comment]
Necesito la vista de registro terminada para realizar la segunda tarea.
