### ISSUE TITLE
Aplicar restricciones teniendo en cuenta el plan contratado

### ISSUE THREAD

**Issue by davdelcar** [ISPP-23-24-Grupo-3/musclemate-frontend#144]

**Comment by AleSosa13** [comment]
El plan contratado es por gimnasios o por dueño?

**Comment by davdelcar** [comment]
A la hora de obtener el plan del owner, ejecutar la función `getOwnerSubscription` y acto seguido se almacenará en el estado `ownerSubscription,` ambos usando el SubscriptionContext.

Para usar ambos, incluir al principio del componente la siguiente linea:
`const {getOwnerSubscription, ownerSubscription } = useContext(SubscriptionContext)`
