### ISSUE TITLE
Feedback Sprint 2 : Ticket

### ISSUE THREAD

**Issue by angmunpri** [ISPP-23-24-Grupo-3/musclemate-frontend#156]
- Los clientes no pueden ver sus tickets tras crearlos, en una vista de tickets.
- No hay validación en los campos.
- El buscador de "ver tickets" (owner) a veces entra en conflicto con la paginación.
- Cuando falla algo, no indica que campo falla.
- Mientras carga el listado (owner) se muestra "no hay tickets disponibles", debería ser un tipo de carga.

- [x] Crear listado de tickets propios para clientes
- [x] Verificar validación de campos y crear errores para cada campo
- [x] Solucionar el conflicto de la búsqueda y la paginación.
- [x] Añadir carga al listado de tickets para owner.
- [x] Desde el listado de máquinas se debe seleccionar automáticamente la máquina del ticket
- [x] (Sugerencia de Piloto) Renombrar los tickets, su nombre no es intuitivo.
- [x] (Sugerencia de Piloto) Poder añadir una imagen al ticket para detallar más problemas.
- [x] (Sugerencia de Piloto) Añadir buscador o filtro al desplegable de las máquinas.

**Comment by AMC112002** [comment]
La tarea de la imágen sera abordada mas adelante cuando se modifique el modelo de ticket en el backend, el equipo de backend ya está informado.
