### ISSUE TITLE
Feedback Sprint 3 (S10) : Aspectos Menores

### ISSUE THREAD

**Issue by angmunpri** [ISPP-23-24-Grupo-3/musclemate-frontend#238]
- En las incidencias no permite buscar un ticket de una página anterior a la actual.
- El buscador de usuarios (dentro del listado) falla a veces.
- La entidad gimnasio lleva a confusiones, se podría editar algunos textos para aclararla.
- Tras seleccionar un filtro en un listado este ha de cerrarse a voluntad.

- [ ] Arreglar el problema con el buscador/paginado de ticket
- [x] Arreglar el buscador de usuario
- [x] Añadir aclaraciones sobre la entidad Gym
- [x] Añadir que al seleccionar un filtro se cierre el listado.

**Comment by lemonada02** [comment]
los tickets estan en arreglo por parte de agustin y del Hoyo
