### ISSUE TITLE
Interfaz gestión de tickets(Gimnasio)

### ISSUE THREAD

**Issue by davdelcar** [ISPP-23-24-Grupo-3/musclemate-frontend#43]
## REQ012:
- Gestión de  reclamaciones por parte del cliente.
- El requisito estará validado cuando el gimnasio pueda dar respuesta a los feedback de sus usuarios.

**Comment by angmunpri** [comment]
A tener en cuenta:
-Los propietarios de los gimnasios no responden directamente al ticket, solo pueden marcarlo como resuelto o no. Si deseasen contactar con el cliente disponen de su información de contacto.
-Se ha decidido enseñar los campos relevantes para el ticket (nombre de maquina, gimnasio, asunto y descripción) así como los campos relevantes del usuario que son su nombre y correo de contacto. 
-Es necesario ciertos ajustes en el backend para poder implementar correctamente el estado de resuelto y añadir el nombre del usuario.
