### ISSUE TITLE
Página principal no carga en frío

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/musclemate-frontend#59]
No se puede arrancar la pagina desde 0 en frio, es decir ejecutando npm run dev solamente (sin backend)

El problema está en el componente `AuthContext.js`

- El estado de loading está a `true` inicialmente por lo que pasa por el if de loading y llama a `updateToken`

```js
useEffect(()=> {
         // Pasa por el if inicialmente
        if(loading){
            updateToken()
        }
      /// Mas codigo...
```
- Dentro de `updateToken` llama a `postToApi` que contiene el siguiente codigo

```js
export function postToApi(url, data) {
  return fetch(`${BASE_URL}/${url}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${JSON.parse(localStorage.getItem('authTokens')).access}`,
    },
    body: JSON.stringify(data),
  });
```
Cuando el localStorage accede a authTokens devuelve `null` porque no tiene en el local storage nada y encima se accede a
una propiedad

```js
// Error por consola
Authorization: `Bearer ${JSON.parse(null).access}`
```
@davdelcar Si le puedes hechar un vistazo

**Comment by pgmarc** [comment]
Lo que he hecho para que me tire al menos la pagina inicial es poner el estado de `loading` a `false`

**Comment by davdelcar** [comment]
He eliminado el estado de loading de forma momentanea para que vaya bien por falta de tiempo, más tarde cuando tenga tiempo lo arreglo de forma correcta.
