### ISSUE TITLE
Refactorizar enrutado y añadir navegación a la barra de navegación

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/musclemate-frontend#75]
# Feedback proporcionado por el grupo 9:
Se aconseja **añadir navegabilidad** a la página ya que para volver atrás a veces hay que recurrir a esta opción en el navegador
en lugar de poder retroceder en la propia página. (Punto 5 del feedback documento)

He estructurado las rutas de la siguiente manera:
- /login
- /register-client
- /owner
  - /home
  - /users
  - /users/register
  - /users/:id/profile
  - /equipments
  - /equipments/add
  - /equipments/:equipmentId
- /user
  - /routines
  - /routines/add
  - /routines/:id
  - /tickets

@ElenaTomasVela  @lemonada02  @angmunpri @luisgp9  @juancarlos1907 @AMC112002  El register client tiene sentido ahora mismo? Al owner del gimasio se le proporiciona unas credenciales no?

La pagina de home del owner se deberia quitar y poner los links en la barra de navegacion.
Si es un owner o un usuario normal renderizamos los links pertinentes. Que pensais?

**Comment by ElenaTomasVela** [comment]
En mi opinión, tanto clientes como propietarios deberían tener una página inicial, que será en un futuro donde se guarden los dashboards.

Por otro lado, no estoy segura en cuanto al registro de clientes. Si mal no recuerdo, se habló que sería el propietario el que registraría al usuario. Los owners definitivamente deberían poder registrarse por su cuenta.

La idea de mostrar solamente los enlaces adecuados para cada tipo de usuario me parece fundamental implementar, así como la estructura que has sugerido, ya que es mucho más intuitiva.

Un añadido adicional que me gustaría que ocurriera fuera que, al hacer un registro o login, te devuelva a la página en la que estabas anteriormente.

**Comment by davdelcar** [comment]
De la navegabilidad me puedo encargar hoy de ello, haré también una página principal para los clientes un poco básica o ver que se me ocurre para rellenarla.
