### ISSUE TITLE
Foto de perfil de los detalles de los usuarios no carga correctamente

### ISSUE THREAD

**Issue by pgmarc** [ISPP-23-24-Grupo-3/musclemate-frontend#85]
# Problema

La imagen de la foto de perfil de los detalles de un usuario no carga correctamente.

# Propuesta solución
Se pueden cargar las imágenes al listar los perfiles en /users. Luego pasas la imagenes por el `Link` y pasarlos por el estado.
Luego utilizas [useLocation](https://reactrouter.com/en/main/hooks/use-location) para traerte la imagen

**Comment by manortgar** [comment]
Según la revisión de @AMC112002 y yo creemos que es por que la lista de los usuarios del gimnasio, carga a todos los usuarios, y los usuarios que no pertenecen a ese gym cargan mal. Creo una issue para solucionar esto.
